databases:
  - name: rendersite
    databaseName: rendersite_f0a3
    user: rendersite

services:
  - type: web
    name: rendersite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn rendersite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4